language: python
python:
  - "3.4"
  - "3.5"
#  - "nightly"

# Environments
env:
  - EVENT_LOOP=asyncio
  - EVENT_LOOP=uvloop

# Install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install make build-essential pkg-config libtool automake -y
  - git clone --depth 1 -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure && make
  - sudo make install
  - sudo ldconfig
  - cd ..
install:
  - pip install .
  - pip install logbook
  - pip install pytest-asyncio pytest-cov
  - pip install codecov
  - ./.travis-install-uvloop.sh

# Run tests
script:
  - ./.travis-run-tests.sh

# After success
after_success:
  - codecov

